# Generated by Django 3.2.9 on 2022-01-06 05:01

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='google_map',
            field=models.CharField(max_length=500, verbose_name='Google Map'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(max_length=10, verbose_name='Place Type'),
        ),
    ]
